<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastNewsByCategory($category, $limit)
    {
        return $this->findBy(
            [
                'active' => '1',
                'category' => $category,
            ],
            ['date' => 'DESC'],
            $limit,
            0
        );
    }

    public function getCategoryByName($name)
    {
        return $this->findBy(

            ['category' => $name]


        );
    }
}
